# Generated by Django 2.1.3 on 2018-12-09 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moisture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1)),
                ('received_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('moisture', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=1)),
                ('recieved_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('temp', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
