# Generated by Django 2.1.3 on 2018-12-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_setpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='setpoint',
            name='pump_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='setpoint',
            name='pump_2',
            field=models.BooleanField(default=False),
        ),
    ]
