# Generated by Django 2.1.3 on 2018-12-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0004_measurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esp', models.BooleanField(default=False)),
                ('pump_1', models.BooleanField(default=False)),
                ('lights', models.BooleanField(default=False)),
                ('pump_2', models.BooleanField(default=False)),
            ],
        ),
    ]
